# from hvr's multi-ghc-travis template

language: haskell

env:
 - CABALVER=1.22 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - sudo apt-get install freeglut3-dev liblapack-dev libblas-dev libgsl0-dev llvm-3.4 llvm-3.4-dev
 - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy alex
 - sudo apt-get install freeglut3-dev liblapack-dev libblas-dev libgsl0-dev
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal-$CABALVER --version
 - travis_retry cabal-$CABALVER update

script:
 - cabal-$CABALVER sandbox init
 - cabal-$CABALVER sandbox add-source tetrode-ephys
 - cabal-$CABALVER sandbox add-source tetrode-graphics
 - cabal-$CABALVER sandbox add-source arte-lib
 - cabal-$CABALVER install tetrode-ephys tetrode-graphics arte-lib arte-command arte-decoder arte-lfp-viewer arte-mock-data arte-spike-viewer only-dependencies
 - cabal-$CABALVER install tetrode-ephys --enable-tests --enable-benchmarks
 - cabal-$CABALVER install tetrode-graphics --enable-tests --enable-benchmarks
 - cabal-$CABALVER install arte-lib --enable-tests --enable-benchmarks
 - cabal-$CABALVER install arte-decoder --enable-tests --enable-benchmarks
 - cabal-$CABALVER install arte-command --enable-tests --enable-benchmarks
 - cabal-$CABALVER install arte-mock-data --enable-tests --enable-benchmarks
