# from hvr's multi-ghc-travis template

env:
 - GHCVER=7.4.1
 - GHCVER=7.4.2
 - GHCVER=7.6.1
 - GHCVER=7.6.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
 - sudo apt-get install git
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.18 update
 - git clone https://github.com/ImAlsoGreg/haskell-tetrode-ephys
 - cabal-1.18 sandbox init
 - cabal-1.18 sandbox add-source haskell-tetrode-ephys
 - cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks

script:
 - cabal-1.18 configure
 - cabal-1.18 build
 - cabal-1.18 install
